### ISSUE TITLE
Dynamic `not` prefixed restrictions

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cborm#27]
Add a method in `Restrictions.cfc` for `isNotIn` which wraps the `isIn` statement in an `isNot`:

```
any function isNotIn(required string property, required any propertyValue){
		// infalte to array if simple values
		if( isSimpleValue(arguments.propertyValue) ){ arguments.propertyValue = listToArray( arguments.propertyValue); }
		return isNot( variables.restrictions.in(arguments.property, arguments.propertyValue) );
}
```

**Comment by lmajano** [comment]
I went a step further and did dynamic negations like we do in TestBox.  You can now negate any criteria restriction by prefixing it with a `not`.  So you can do: `.notEq(), notBetween(), notIsNull(), notIsIn()` and much more.

**Comment by jclausen** [comment]
Awesome! :)
